### PR TITLE
Create fa_IR.tsx

### PR DESCRIPTION
**Pull request by farskid**
Added locale of Farsi/Persian language

### CODE REVIEW

**Comment by farskid** [comment]
@yiminghe Is it something wrong with lint command?

**Comment by silentcloud** [comment]
@farskid 

image

**Comment by farskid** [comment]
@silentcloud Seems I can't install `rc-tools`. keeps throwing error on me. anyway around it to run the linter?

**Comment by farskid** [comment]
~ping @silentcloud

**Comment by yiminghe** [comment]
try yarn

**Pull request merged**
